baseURL: "https://ai-co-blog.vercel.app/"
languageCode: "zh-tw"
title: "AI å…±ç­†éƒ¨è½æ ¼"
theme: "PaperMod"
paginate: 10

# taxonomies:
#   category: categories
#   tag: tags

# permalinks:
#   tags: "/tags/:slug/"

menu:
  main:
    - identifier: "archives"
      name: "æ‰€æœ‰æ–‡ç« "
      url: "/archives/"
      weight: 10
    - identifier: "search"
      name: "æœå°‹"
      url: "/search/"
      weight: 20
    # - identifier: "tags"
    #   name: "æ¨™ç±¤"
    #   url: "/tags/"
    #   weight: 30

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"

params:
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 1
    minMatchCharLength: 0
    keys: ["title", "summary", "content"] # "permalink",

  authors: ["Daniel", "Shirley", "Wally", "Winnie", "ç‘œæ¥“"]
  ShowCodeCopyButtons: true
  ShowBreadCrumbs: true
  ShowToc: true
  TocOpen: true
  enableSearch: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowReadingTime: true
  ShowAllPagesInArchive: true

  homeInfoParams:
    Title: "æ­¡è¿ä¾†åˆ° AI å…±ç­†éƒ¨è½æ ¼ ğŸ‘‹"
    Content: "æ¯é€±åˆ†äº« AI ç›¸é—œçŸ¥è­˜å’Œå¥½ç”¨å·¥å…·ï¼Œæ­¡è¿åŠ å…¥æˆ‘å€‘ï¼Œä¸€èµ·æ¢ç´¢ AI çš„ç„¡é™å¯èƒ½ï¼"

  socialIcons:
    - name: "discord"
      url: "https://discord.gg/BCbAYf7pkA"
    - name: "github"
      url: "https://github.com/arealclimber/ai-collaborative-blog"
